include ./nord.conf
include ~/github/dotfiles-latest/kitty/active-theme.conf

background_opacity 0.7

font_family Iosevka Term
font_size 	    18
modify_font cell_width 95%
bold_font       auto
italic_font      auto
bold_italic_font auto

confirm_os_window_close 0

window_padding_width 5

cursor_shape beam
cursor_beam_thickness 1.5
cursor_underline_thickness 2.0

cursor_blink_interval -1

cursor_stop_blinking_after 15.0

cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2
