#include ~/.cache/wal/colors-kitty.conf
font_family Iosevka Term
font_size 	    18
bold_font       auto
italic_font      auto
bold_italic_font auto

text_composition_strategy legacy

# Cursor trail configuration
cursor_trail 10            # Increased to 100ms for more visible trail
cursor_trail_start_threshold 5  # Keep at 0 to show trail at any speed

background_opacity 0.7

confirm_os_window_close 0

enable_audio_bell no

selection_foreground #000000
selection_background #F5FBFF

include ./nord.conf

window_padding_width 5

# Add URL handling
url_color #0087bd
url_style curly
detect_urls yes
