#!/bin/bash
# Generated by switchwall.sh - Don't modify it by yourself.
# Time: Do 22. Mai 15:06:02 CEST 2025

pkill -f -9 mpvpaper

for monitor in $(hyprctl monitors -j | jq -r '.[] | .name'); do
    mpvpaper -o "no-audio loop hwdec=auto scale=bilinear interpolation=no video-sync=display-resample panscan=1.0 video-scale-x=1.0 video-scale-y=1.0 video-align-x=0.5 video-align-y=0.5" "$monitor" "/home/aki/Bilder/Wallpapers/MuZS7rf2On-Sequengtgce012Prob4.mp4" &
    sleep 0.1
done
