# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# Custom window rules for specific applications

# Cursor
windowrulev2 = opacity 0.9 0.8, class:^(cursor)$

# Terminal (kitty) — transparency handled via kitty's background_opacity instead
# windowrulev2 = opacity 0.6 0.6, class:^(kitty)$

# Zen Browser
windowrulev2 = opacity 1, class:^(zen)$


# Minecraft
windowrulev2 = opacity 1, class:^(com\.mojang\.minecraft\.java-edition)$
windowrulev2 = workspace 2, class:^(com\.mojang\.minecraft\.java-edition)$

# Vesktop
windowrulev2 = opacity 0.85, class:^(vesktop)$
