# ==============================================================================
# USER CONFIGURATION: monitors.conf
# ==============================================================================
# Add your custom settings for monitors here.
# These will override or add to the defaults found in ~/.config/hypr/source/monitors
# This file can also be edited with dusky monitor from the rofi menu or from dusky control center
# ==============================================================================

monitor=DP-3,3440x1440@165,auto, 1
