# ==============================================================================
# USER CONFIGURATION: window_rules.conf
# ==============================================================================
# Add your custom settings for window_rules here.
# These will override or add to the defaults found in ~/.config/hypr/source/window_rules.conf
# ==============================================================================

# -----------------------------------------------------
# ✳ Claude Code
windowrule {
    name = kitty
    match:class = ^(kitty)$
    # match:title = ^(✳ Claude Code)$
    float = off
    # pin = on
    size = 3416 1378
    # size = (monitor_w*0.9930) (monitor_h*0.9569)
    move = 12 12
    # move = (monitor_w*0.0035) (monitor_h*0.0083)
    # move = (monitor_w-window_w-20) (monitor_h-window_h-20)
    # center = on

    # --- Visuals & Effects ---
    # opacity [active] [inactive]
    opacity = 0.9 1
    # animation = popin
    # rounding = 10
    # border_color = rgb(ff0000)
    no_blur = on
    # no_shadow = on
    no_dim = on
    # opaque = on
    # dim_around = on

    # --- Placement ---
    # workspace = 2
    # monitor = DP-1
}

windowrule {
    name = firefox 
    match:class = ^(firefox)$
    float = off
    # pin = on
    size = 3416 1378
    # size = (monitor_w*0.9930) (monitor_h*0.9569)
    move = 12 12
    # move = (monitor_w*0.0035) (monitor_h*0.0083)
    # move = (monitor_w-window_w-20) (monitor_h-window_h-20)
    # center = on

    # --- Visuals & Effects ---
    # opacity [active] [inactive]
    opacity = 1 1
    # animation = popin
    # rounding = 10
    # border_color = rgb(ff0000)
    # no_blur = on
    # no_shadow = on
    no_dim = on
    opaque = on
    # dim_around = on

    # --- Placement ---
    # workspace = 2
    # monitor = DP-1
}
# -----------------------------------------------------
# Google — Zen Browser
windowrule {
    name = zen
    match:class = ^(zen)$
    float = off
    # pin = on
    size = 1700 1376
    # size = (monitor_w*0.4942) (monitor_h*0.9556)
    move = 1727 13
    # move = (monitor_w*0.5020) (monitor_h*0.0090)
    # move = (monitor_w-window_w-20) (monitor_h-window_h-20)
    # center = on

    # --- Visuals & Effects ---
    # opacity [active] [inactive]
    opacity = 1 override 1 override
    # animation = popin
    # rounding = 10
    # border_color = rgb(ff0000)
    no_blur = on
    # no_shadow = on
    no_dim = on
    # opaque = on
    # dim_around = on

    # --- Placement ---
    # workspace = 2
    # monitor = DP-1
}

