[color]
background = 'default'
foreground = '#c57b95'

; gradient = 0
gradient = 1
gradient_color_1 = '#60263d'
gradient_color_2 = '#c57b95'
gradient_color_3 = '#db8ea8'

horizontal_gradient = 0
; horizontal_gradient = 1
horizontal_gradient_color_1 = '#60263d'
horizontal_gradient_color_2 = '#c57b95'
horizontal_gradient_color_3 = '#db8ea8'
horizontal_gradient_color_4 = '#c57b95'
horizontal_gradient_color_5 = '#60263d'


