[color]
background = 'default'
foreground = '#5599b9'

; gradient = 0
gradient = 1
gradient_color_1 = '#003f54'
gradient_color_2 = '#5599b9'
gradient_color_3 = '#69accd'

horizontal_gradient = 0
; horizontal_gradient = 1
horizontal_gradient_color_1 = '#003f54'
horizontal_gradient_color_2 = '#5599b9'
horizontal_gradient_color_3 = '#69accd'
horizontal_gradient_color_4 = '#5599b9'
horizontal_gradient_color_5 = '#003f54'


