# : Manager [[[

[mgr]
cwd = { fg = "#ad9fa2" }

# Find
find_keyword  = { fg = "#ff5449", bold = true, italic = true, underline = true }
find_position = { fg = "#ff5449", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#b87a46", bg = "#b87a46" }
marker_cut      = { fg = "#6e492a", bg = "#6e492a" }
marker_marked   = { fg = "#ff5449", bg = "#ff5449" }
marker_selected = { fg = "#b58763", bg = "#b58763" }

# Count
count_copied   = { fg = "#edba92", bg = "#6e492a" }
count_cut      = { fg = "#edba92", bg = "#6e492a" }
count_selected = { fg = "#6d3148", bg = "#b58763" }

# Border
border_symbol = "│"
border_style  = { fg = "#ffb0ca" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "█", close = "█" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#c57b95", bold = true, bg = "#191114" }
inactive  = { fg = "#a98892", bg = "#191114" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#c57b95", fg = "#6d3148", bold = true }
normal_alt  = { bg = "#514347", fg = "#907f83" }

# Select mode
select_main = { bg = "#a98892", fg = "#3a232b", bold = true }
select_alt  = { bg = "#514347", fg = "#907f83" }

# Unset mode
unset_main = { bg = "#b58763", fg = "#402207", bold = true }
unset_alt  = { bg = "#514347", fg = "#907f83" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "🭁", close = "🭠" }
sep_right = { open = "🭁", close = "🭠" }

# Permissions
perm_type  = { fg = "#584047" }
perm_write = { fg = "#563d29" }
perm_read  = { fg = "#af0b00" }
perm_exec  = { fg = "#c6946b" }
perm_sep   = { fg = "#c68ba2" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#c57b95", bg = "#403739" }
progress_error  = { fg = "#ff5449", bg = "#403739" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#403739" }
cand = { fg = "#c57b95" }
rest = { fg = "#6d3148" }
desc = { fg = "#ad9fa2" }
separator = " ▶ "
separator_style = { fg = "#ad9fa2" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#b58763" }
title_warn  = { fg = "#c57b95" }
title_error = { fg = "#ff5449" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#c57b95" }
active = { fg = "#b58763", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#c57b95" }
value  = { fg = "#ad9fa2" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#c57b95", bg = "#6d3148" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#c57b95" }
title   = {}
hovered = { fg = "#6e492a", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#ad9fa2" }
run    = { fg = "#ad9fa2" }
footer = { fg = "#3a232b", bg = "#a98892" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#7b0007" },
    { name = "*", is = "exec", fg = "#ff7d70" },

    # Fallback
    { url = "*", fg = "#ad9fa2" },
    { url = "*/", fg = "#ffb0ca" },
]

# : ]]]
