-- Auto-generated by Matugen — Material You colors for Neovim
return {
  primary               = "{{colors.primary.default.hex}}",
  on_primary            = "{{colors.on_primary.default.hex}}",
  primary_container     = "{{colors.primary_container.default.hex}}",
  on_primary_container  = "{{colors.on_primary_container.default.hex}}",
  primary_fixed_dim     = "{{colors.primary_fixed_dim.default.hex}}",

  secondary             = "{{colors.secondary.default.hex}}",
  on_secondary          = "{{colors.on_secondary.default.hex}}",
  secondary_container   = "{{colors.secondary_container.default.hex}}",
  on_secondary_container = "{{colors.on_secondary_container.default.hex}}",
  secondary_fixed_dim   = "{{colors.secondary_fixed_dim.default.hex}}",

  tertiary              = "{{colors.tertiary.default.hex}}",
  on_tertiary           = "{{colors.on_tertiary.default.hex}}",
  tertiary_container    = "{{colors.tertiary_container.default.hex}}",
  on_tertiary_container = "{{colors.on_tertiary_container.default.hex}}",
  tertiary_fixed_dim    = "{{colors.tertiary_fixed_dim.default.hex}}",

  error                 = "{{colors.error.default.hex}}",
  error_container       = "{{colors.error_container.default.hex}}",

  background            = "{{colors.background.default.hex}}",
  on_background         = "{{colors.on_background.default.hex}}",
  surface               = "{{colors.surface.default.hex}}",
  on_surface            = "{{colors.on_surface.default.hex}}",
  on_surface_variant    = "{{colors.on_surface_variant.default.hex}}",
  surface_container     = "{{colors.surface_container.default.hex}}",
  surface_container_high = "{{colors.surface_container_high.default.hex}}",

  outline               = "{{colors.outline.default.hex}}",
  outline_variant       = "{{colors.outline_variant.default.hex}}",
}
